In [2]:
import torch
from torch import nn

In [3]:
net = nn.Sequential(
    nn.LazyLinear(8),
    nn.ReLU(),
    nn.LazyLinear(1)
)
X = torch.rand((2, 4))
net(X).shape

torch.Size([2, 1])

In [7]:
def init_normal(modul):
    if type(modul) == nn.Linear:
        nn.init.normal_(modul.weight, mean=0, std=0.01)
        nn.init.zeros_(modul.bias)
net.apply(init_normal)
net[0].weight.data[0], net[0].bias.data[0]

(tensor([-0.0065,  0.0024,  0.0043, -0.0056]), tensor(0.))

In [8]:
def init_constant(modul):
    if type(modul) == nn.Linear:
        nn.init.constant_(modul.weight, 1)
        nn.init.zeros_(modul.bias)
net.apply(init_constant)
net[0].weight.data[0], net[0 ].bias.data[0]

(tensor([1., 1., 1., 1.]), tensor(0.))

In [9]:
def init_xavier(modul):
     if type(modul) == nn.Linear:
        nn.init.xavier_uniform_(modul.weight)
def init_42(modul):
     if type(modul) == nn.Linear:
        nn.init.constant_(modul.weight, 42)

net[0].apply(init_xavier)
net[2].apply(init_42)
print(net[0].weight.data[0])
print(net[2].weight.data[0])

tensor([-0.1346,  0.2878,  0.5647, -0.5422])
tensor([42., 42., 42., 42., 42., 42., 42., 42.])


In [10]:
def my_init(modul):
    if type(modul) == nn.Linear:
        print(f"Init", *[(name, param.shape) for name, param in modul.named_parameters()][0])
        
        nn.init.uniform_(modul.weight, -10, 10)
        modul.weight.data *= modul.weight.data.abs() >= 5
net.apply(my_init)
net[0].weight[:2]

Init weight torch.Size([8, 4])
Init weight torch.Size([1, 8])


tensor([[ 8.4696,  0.0000, -0.0000, -0.0000],
        [-0.0000,  0.0000, -5.0438, -0.0000]], grad_fn=<SliceBackward0>)