In [1]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [5]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())
Y = net(torch.rand(8, 10))
Y.mean()

tensor(1.8626e-09, grad_fn=<MeanBackward0>)

In [15]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.rand((in_units, units)))
        self.bias = nn.Parameter(torch.zeros((units, )))
    
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [16]:
linear = MyLinear(in_units=5, units=3)
linear.weight

Parameter containing:
tensor([[0.1256, 0.4268, 0.3583],
        [0.3929, 0.2278, 0.8615],
        [0.3595, 0.2987, 0.6767],
        [0.5393, 0.0552, 0.1679],
        [0.4240, 0.8483, 0.1538]], requires_grad=True)

In [17]:
linear(torch.rand(2, 5))

tensor([[0.9821, 0.7527, 1.1809],
        [0.6410, 0.8661, 0.4835]])

In [18]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[94.2251],
        [86.2843]])