In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [4]:
path = 'My_data/'
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [6]:
torch.save(x, path + 'x-file')

In [8]:
x2 = torch.load(path+'x-file', weights_only=True)
x2

tensor([0, 1, 2, 3])

In [9]:
y = torch.zeros(4)
torch.save([x, y], path + 'x-file')

In [12]:
x2, y2 = torch.load(path + 'x-file', weights_only=True)

In [13]:
x2, y2

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [14]:
my_dict = {'x':x, 'y':y}
torch.save(my_dict, path+'mydict')
my_dict2 = torch.load(path+'mydict', weights_only=True)

In [15]:
my_dict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [18]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.LazyLinear(256)
        self.output = nn.LazyLinear(10)
    def forward(self, X):
        return self.output(F.relu(self.hidden(X)))

In [26]:
net = MLP()
X = torch.rand(size=(2, 10))
Y = net(X)

In [27]:
torch.save(net.state_dict(), 'mlp.params')

In [28]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params', weights_only=True))

<All keys matched successfully>

In [29]:
clone.eval()

MLP(
  (hidden): LazyLinear(in_features=0, out_features=256, bias=True)
  (output): LazyLinear(in_features=0, out_features=10, bias=True)
)

In [30]:
y_clone = clone(X)
y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])